plugins {
    id 'org.springframework.boot' version '4.0.8' apply false
    id 'io.spring.dependency-management' version '1.1.7' apply false
}



allprojects {
    group = 'com.sajo'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

def libsProjects = subprojects.findAll { it.path == ':libs' || it.path.startsWith(':libs:') }
def serviceProjects = subprojects.findAll { !(it.path == ':libs' || it.path.startsWith(':libs:')) }

configure(serviceProjects) {
    apply plugin: 'java'
    apply plugin: 'org.springframework.boot'
}

configure(libsProjects) {
    apply plugin: 'java-library'
}

subprojects {
    apply plugin: 'io.spring.dependency-management'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }
}