services:
  postgres-user-account:
    image: postgres:17-alpine
    container_name: sajo-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"

  postgres-market-strategy:
    image: postgres:17-alpine
    container_name: sajo-postgres-market-strategy
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: market_strategy_db
    ports:
      - "5433:5432"

  postgres-trading:
    image: postgres:17-alpine
    container_name: sajo-postgres-trading
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trading_db
    ports:
      - "5434:5432"

  mongo-ai-risk:
    image: mongo:8.0
    container_name: sajo-mongo-ai-risk
    ports:
      - "27017:27017"