server:
  port: 8080

spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  cloud:
    gateway:
      server.webmvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/USER-SERVICE/**
            filters:
              - StripPrefix=1
          - id: market-service
            uri: lb://market-service
            predicates:
              - Path=/MARKET-SERVICE/**
            filters:
              - StripPrefix=1
          - id: trading-service
            uri: lb://trading-service
            predicates:
              - Path=/TRADING-SERVICE/**
            filters:
              - StripPrefix=1
    config:
      retry:
        max-attempts: 10
        initial-interval: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

---
spring:
  config:
    activate:
      on-profile: local

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: prod

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
