server:
  port: 8080

spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    config:
      retry:
        max-attempts: 10
        initial-interval: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

---
spring:
  config:
    activate:
      on-profile: local

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: prod

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
