global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: discovery-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["discovery-service:8761"]
        labels:
          application: discovery-service

  - job_name: gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["gateway:8080"]
        labels:
          application: gateway

  - job_name: user-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["user-service:8081"]
        labels:
          application: user-service

  - job_name: market-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["market-service:8082"]
        labels:
          application: market-service

  - job_name: trading-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["trading-service:8083"]
        labels:
          application: trading-service

  - job_name: operation-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["operation-service:8084"]
        labels:
          application: operation-service

  - job_name: redis
    static_configs:
      - targets: ["redis-exporter:9121"]
        labels:
          application: redis

  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          application: postgres

  - job_name: kafka
    static_configs:
      - targets: ["kafka-exporter:9308"]
        labels:
          application: kafka

  - job_name: mongo
    static_configs:
      - targets: ["mongo-exporter:9216"]
        labels:
          application: mongo

  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          application: node