server:
  port: 8083

spring:
  application:
    name: trading-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  cloud:
    config:
      retry:
        max-attempts: 10
        initial-interval: 2000

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:dummy-key-for-tests}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/sajo?currentSchema=trading
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        default_schema: trading
    hibernate:
      ddl-auto: update
  mongodb:
    uri: mongodb://localhost:27017/ai_risk_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres:5432/sajo?currentSchema=trading
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: trading
    hibernate:
      ddl-auto: validate
  mongodb:
    uri: mongodb://mongo-ai-risk:27017/ai_risk_db
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: trading-consumer-group

sajo:
  kafka:
    type-mappings:
      trading.signal.generated: com.sajo.trading_service.trading.kafka.dto.TradingSignalGeneratedEvent

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
