server:
  port: 8081

spring:
  application:
    name: user-service
---
spring:
  config:
    activate:
      on-profile: local
    import: "optional:configserver:http://localhost:8888"
---
spring:
  config:
    activate:
      on-profile: prod
    import: "optional:configserver:http://config-server:8888"
  cloud:
    config:
      retry:
        max-attempts: 10
        initial-interval: 2000
