spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service-route
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v1/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka