server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sajo-team/sajo-config-repo.git
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}
          default-label: main


encrypt:
  key: ${ENCRYPT_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
